"""add column

Revision ID: 4e614956af39
Revises: 85d09fc9aa83
Create Date: 2022-07-12 17:55:38.289957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e614956af39'
down_revision = '85d09fc9aa83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('add_column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'add_column')
    # ### end Alembic commands ###
