"""create demo table

Revision ID: 85d09fc9aa83
Revises: 77015c7bf65a
Create Date: 2022-07-12 17:54:14.534186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d09fc9aa83'
down_revision = '77015c7bf65a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
